src/components.d.ts, src/components/dropdown-menu/dropdown-menu.scss, src/components/dropdown/dropdown.stories.ts, src/components/dropdown/dropdown.tsx, src/components/filter-input/filter-input.scss, src/components/filter-input/filter-input.tsx, src/components/filter-input/readme.md, src/index.html, src/index.scss
Renamed ifx-dropdown-filter with ifx-filter-input 
<details>
<summary>📦 Published PR as canary version: <code>0.0.64--canary.29.3d48eb41a939f727d64d5f52d030980c2fb26235.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@0.0.64--canary.29.3d48eb41a939f727d64d5f52d030980c2fb26235.0
yarn add @infineon/infineon-design-system-stencil@0.0.64--canary.29.3d48eb41a939f727d64d5f52d030980c2fb26235.0
```
</details>
=> replaced dropdown-filter with filter-input

src/components.d.ts, src/components/dropdown-divider/dropdown-divider.scss, src/components/dropdown-divider/dropdown-divider.tsx, src/components/dropdown-divider/readme.md, src/components/dropdown-item/dropdown-item.tsx, src/components/dropdown-item/readme.md, src/components/dropdown-menu/dropdown-menu.scss, src/components/dropdown-menu/dropdown-menu.tsx, src/components/dropdown-menu/readme.md, src/components/dropdown/dropdown.tsx, src/components/icon/readme.md, src/components/select-input/readme.md, src/components/select-input/select-input.scss, src/components/select-input/select-input.stories.ts, src/components/select-input/select-input.tsx, src/components/text-input/readme.md, src/components/text-input/text-input.scss, src/components/text-input/text-input.tsx, src/index.html, src/index.scss
The Select Component version 2
v-1: without divider
v-2: divider inside dropdown-menu
v-3: checkbox
v-4: when menu is at the bottom
v-5: multi-select?
<details>
<summary>📦 Published PR as canary version: <code>18.0.16--canary.132.f8f375feb66e3cc99fbb5916f51c732aa6f2c244.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@18.0.16--canary.132.f8f375feb66e3cc99fbb5916f51c732aa6f2c244.0
yarn add @infineon/infineon-design-system-stencil@18.0.16--canary.132.f8f375feb66e3cc99fbb5916f51c732aa6f2c244.0
```
</details>
=> 131 select input v-2

packages/components/src/components/search-field/search-field.scss, packages/components/src/components/search-field/search-field.tsx, packages/components/src/components/tooltip/tooltip.scss, packages/components/src/index.html
Removed the addition of 'search-field__wrapper-m' from JS and SCSS. 
<details>
<summary>📦 Published PR as canary version: <code>20.16.4--canary.474.1bc08eb13cce58543590381c5af692085b8caadc.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.16.4--canary.474.1bc08eb13cce58543590381c5af692085b8caadc.0
yarn add @infineon/infineon-design-system-stencil@20.16.4--canary.474.1bc08eb13cce58543590381c5af692085b8caadc.0
```
</details>
=> Search-field height issue

packages/components/src/components/dropdown/dropdown-menu/dropdown-menu.scss
Only added position: relative to :host { .. } in dropdown-menu. 
<details>
<summary>📦 Published PR as canary version: <code>20.16.4--canary.472.18eb86085183bcb52929f1b1664f2c24e244a7b2.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.16.4--canary.472.18eb86085183bcb52929f1b1664f2c24e244a7b2.0
yarn add @infineon/infineon-design-system-stencil@20.16.4--canary.472.18eb86085183bcb52929f1b1664f2c24e244a7b2.0
```
</details>
=> added z-index to dropdown-menu

packages/components/src/components/card/card.stories.ts, packages/components/src/components/icon/infineonIconStencil.stories.ts, packages/components/src/components/navbar/navbar.stories.ts, packages/components/src/components/text-field/text-field.stories.ts
Replaced the icon string control in Storybook with a list of all the icons for the few components where it was missing: Card, Icon, Navbar and Text-Field
<details>
<summary>📦 Published PR as canary version: <code>20.23.10--canary.571.e751ee2840f3aea5106a4ac90840d75de379eeaf.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.23.10--canary.571.e751ee2840f3aea5106a4ac90840d75de379eeaf.0
yarn add @infineon/infineon-design-system-stencil@20.23.10--canary.571.e751ee2840f3aea5106a4ac90840d75de379eeaf.0
```
</details>
=> Icons in Storybook: Replaced string with select list

packages/components/src/components/navbar/navbar.tsx, packages/components/src/index.html
Fixed the assignedNodes error by simply putting creating a condition where the assignedNodes method is invoked only if slots exist. 
<details>
<summary>📦 Published PR as canary version: <code>20.23.10--canary.564.d8ca8ea4e67ed6d5082f891782d750c7b4e82188.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.23.10--canary.564.d8ca8ea4e67ed6d5082f891782d750c7b4e82188.0
yarn add @infineon/infineon-design-system-stencil@20.23.10--canary.564.d8ca8ea4e67ed6d5082f891782d750c7b4e82188.0
```
</details>
=> Navbar: assignedNodes error 

packages/components/src/components/alert/alert.scss, packages/components/src/components/badge/badge.scss, packages/components/src/components/breadcrumb/breadcrumb.scss, packages/components/src/components/button/button.scss, packages/components/src/components/card/card.scss, packages/components/src/components/icon-button/icon-button.scss, packages/components/src/components/link/link.scss, packages/components/src/components/list-group/list-group.scss, packages/components/src/components/navbar/navbar.scss, packages/components/src/components/number-indicator/number-indicator.scss, packages/components/src/components/pagination/pagination.scss, packages/components/src/components/progress-bar/progress-bar.scss, packages/components/src/components/radio-button/radio-button.scss, packages/components/src/components/search-bar/search-bar.scss, packages/components/src/components/search-field/search-field.scss, packages/components/src/components/sidebar/sidebar.scss, packages/components/src/components/tabs/tabs.scss, packages/components/src/components/tag/tag.scss, packages/components/src/components/text-field/text-field.scss, packages/components/src/components/tooltip/tooltip.scss
Some of the components did not have a display property set on their :host wrapper. I have added it to those that were missing it. This was necessary for allowing users to add margin or other needed attributes to the component wrappers.
<details>
<summary>📦 Published PR as canary version: <code>20.23.10--canary.560.e3e79bbfacc3c1b1dc7c8a58f857ccf951ef0810.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.23.10--canary.560.e3e79bbfacc3c1b1dc7c8a58f857ccf951ef0810.0
yarn add …
```
=> Ddded display property to the missing components

packages/components/src/components/button/button.stories.ts, packages/components/src/components/checkbox/checkbox.stories.ts, packages/components/src/components/dropdown/dropdown.stories.ts, packages/components/src/components/icon-button/icon-button.stories.ts, packages/components/src/components/link/link.stories.ts
Added size description to the following components in storybook: 
- button 
- checkbox 
- dropdown 
- icon button 
- link 
- radio button
<details>
<summary>📦 Published PR as canary version: <code>20.23.14--canary.582.8eb2b01679cfe3ed49b975737022fcfb51e6d3da.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.23.14--canary.582.8eb2b01679cfe3ed49b975737022fcfb51e6d3da.0
yarn add @infineon/infineon-design-system-stencil@20.23.14--canary.582.8eb2b01679cfe3ed49b975737022fcfb51e6d3da.0
```
</details>
=> added size description to remaining components in storybook

packages/components-vue/lib/components.ts, packages/components/src/components/select/multi-select/Development.mdx, packages/components/src/components/select/multi-select/multiselect.stories.ts, packages/components/src/components/select/multi-select/multiselect.tsx, packages/components/src/components/select/multi-select/readme.md
Description
Placeholder is not a modifiable property for the multiselect component on Storybook.
<details>
<summary>📦 Published PR as canary version: <code>20.23.15--canary.595.bd7a55e58b6c9c10638afe7ab856b6fe40ad09ee.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.23.15--canary.595.bd7a55e58b6c9c10638afe7ab856b6fe40ad09ee.0
yarn add @infineon/infineon-design-system-stencil@20.23.15--canary.595.bd7a55e58b6c9c10638afe7ab856b6fe40ad09ee.0
```
</details>
=> Feature for multiselect - placeholder prop now modifiable

packages/components/src/components/select/single-select/select.scss
Description
border-radius of the select-input was incorrect
Related Issue
#586 
<details>
<summary>📦 Published PR as canary version: <code>20.23.16--canary.591.2bbddb10211f8bf01f8100019e7eb643ce8b161b.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.23.16--canary.591.2bbddb10211f8bf01f8100019e7eb643ce8b161b.0
yarn add @infineon/infineon-design-system-stencil@20.23.16--canary.591.2bbddb10211f8bf01f8100019e7eb643ce8b161b.0
```
</details>
=> fixed border-radius for select-component

packages/components/src/components/navbar/navbar.stories.ts
Removed the icon string control option from the navbar stories. 
The select list of all the icons is now the only icon control option. 
<details>
<summary>📦 Published PR as canary version: <code>20.23.14--canary.579.bd94ee4632ffd8b980211c960c8debae3534e2a9.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.23.14--canary.579.bd94ee4632ffd8b980211c960c8debae3534e2a9.0
yarn add @infineon/infineon-design-system-stencil@20.23.14--canary.579.bd94ee4632ffd8b980211c960c8debae3534e2a9.0
```
</details>
=> Navbar: removed the icon string control option. 

packages/components/src/components/card/card.stories.ts, packages/components/src/components/navbar/navbar.stories.ts, packages/components/src/components/tag/tag.stories.ts, packages/components/src/components/text-field/text-field.stories.ts
Added a default icon on the text-field and tag components in storybook, and removed the icon control from the Card on storybook.
<details>
<summary>📦 Published PR as canary version: <code>20.23.14--canary.580.e3dc5548a8816aaa52809275f2eeeb3bc3988962.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.23.14--canary.580.e3dc5548a8816aaa52809275f2eeeb3bc3988962.0
yarn add @infineon/infineon-design-system-stencil@20.23.14--canary.580.e3dc5548a8816aaa52809275f2eeeb3bc3988962.0
```
</details>
=> Icons on Storybook: added default icon on text-field and tag.

examples/wrapper-components/react-javascript/src/components/Accordion/Accordion.js, packages/components-vue/lib/components.ts, packages/components/src/components/accordion/accordion.stories.tsx, packages/components/src/components/accordion/accordion.tsx, packages/components/src/components/accordion/accordionItem.tsx, packages/components/src/components/accordion/readme.md
Updated the accordion, and added initial-collapse property to accordion-items.
<details>
<summary>📦 Published PR as canary version: <code>20.24.0--canary.617.e7123b3016273f6359220dbc910bca6650463ede.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.24.0--canary.617.e7123b3016273f6359220dbc910bca6650463ede.0
yarn add @infineon/infineon-design-system-stencil@20.24.0--canary.617.e7123b3016273f6359220dbc910bca6650463ede.0
```
</details>
=> Accordion: added initial-collapse Prop on accordion-items

packages/components/src/components/card/card.stories.ts, packages/components/src/components/card/card.tsx, packages/components/src/index.html
Made the href on the Card body undefined if it's empty. This prevents empty redirection.
Also, made a small update to the focus state function. The referenced upperbody element was not being referenced correctly, so I just changed the query element, and now it's working as was intended.
<details>
<summary>📦 Published PR as canary version: <code>20.23.19--canary.615.a73a8bb641de3727218fabb590dfbed8aa61736c.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.23.19--canary.615.a73a8bb641de3727218fabb590dfbed8aa61736c.0
yarn add …
```
=> Card: disabled href when it's empty

.github/dependabot.yml, .github/workflows/target.yml
Description
dependabot.yml file updated to watch for changes in the Infineon-Icons and Infineon-Design-System-Tokens repository.
<details>
<summary>📦 Published PR as canary version: <code>20.25.1--canary.628.49237acde671d771c4c7646f4a2c9959fc10fa3e.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.25.1--canary.628.49237acde671d771c4c7646f4a2c9959fc10fa3e.0
yarn add @infineon/infineon-design-system-stencil@20.25.1--canary.628.49237acde671d771c4c7646f4a2c9959fc10fa3e. …
```
=> dependabot file updated to watch icons and tokens repository

packages/components/package.json
Reverts Infineon/infineon-design-system-stencil#636
not compatible with current stencil version
=> Revert "Bump @types/jest from 27.5.2 to 29.5.6 in /packages/components"

packages/components/src/components/modal/modal.scss, packages/components/src/components/modal/modal.tsx
Modal height is not fixed anymore. It is now adjusted to content. 
<details>
<summary>📦 Published PR as canary version: <code>20.37.2--canary.843.8eb7988eb4ffd2b81ab3469aa399b2369a1c6444.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.37.2--canary.843.8eb7988eb4ffd2b81ab3469aa399b2369a1c6444.0
yarn add @infineon/infineon-design-system-stencil@20.37.2--canary.843.8eb7988eb4ffd2b81ab3469aa399b2369a1c6444.0
```
</details>
=> Modal: height is made adjust-to-content, and not fixed

examples/wrapper-components/react-javascript/src/App.scss, examples/wrapper-components/vue-javascript/src/assets/base.scss, packages/components/src/global/font.scss, packages/components/src/stories/setup-and-installation/GettingStarted.stories.mdx
… the user
Description
Using custom css properties (ifx-font-family) to allow the user to overwrite the default font.
e.g.: in Vue:
For instance, if the Stencil components are all within a certain class (my-app), we can do the following:
```
.my-app {
--ifx-font-family: Times New Roman;
}
```
<details>
<summary>📦 Published PR as canary version: <code>20.38.1--canary.857.4776c3acc5b671cff94df6564063e083bc748c29.0</code></summary>
<br />
```bash
npm install …
```
=> Using CSS Custom Properties to enable overwriting the default font

.github/workflows/shipit_master_and_example_apps_deployment.yml
Description
version wasnt set correctly for the angular wrapper during the master deployment
<details>
<summary>📦 Published PR as canary version: <code>20.38.2--canary.859.c63546d0338e675e10a886dbcd5cb0963a6dc310.1</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.38.2--canary.859.c63546d0338e675e10a886dbcd5cb0963a6dc310.1
yarn add @infineon/infineon-design-system-stencil@20.38.2--canary.859.c63546d0338e675e10a886dbcd5cb0963a6dc310.1
```
</details>
=> bugfix in master .yml

.github/workflows/shipit_master_and_example_apps_deployment.yml, .github/workflows/shipit_pr_and_example_apps_deployment.yml
Description
Every time after a successful deployment to master, the newly added webex integration will make sure that a bot sends a message in our webex space, notifying users of a new version.
At this stage, this PR includes a test, that is also triggered when a commit to this PR is made, that is sent to a test webex space.
<details>
<summary>📦 Published PR as canary version: <code>20.53.0--canary.1033.2d7cae7ea09921016ac53c63cfc11a3fcef3c6e6.0</code></summary>
<br />
```bash
npm install …
```
=> Enhancement: Webex notification on new version release

.github/workflows/shipit_master_and_example_apps_deployment.yml
Description
Bugfix: Version added as Github Output during the deployment action so it can be later retrieved by the send-webex-notification job
<details>
<summary>📦 Published PR as canary version: <code>20.53.1--canary.1040.4708b2ad215b507132e329a5fa189eb355500a97.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.53.1--canary.1040.4708b2ad215b507132e329a5fa189eb355500a97.0
yarn add @infineon/infineon-design-system-stencil@20.53.1--canary.1040.4708b2ad215b507132e329a …
```
=> Bugfix: Version is null when sending webex notification

.github/workflows/shipit_pr_and_example_apps_deployment.yml
Description
Since secrets like the NPM_TOKEN are not accessible to outside contributors like dependabot, the workflows triggered on a dependabot PR always.
Add a simple check, if the PR is created by dependabot, and in that case, simply skip the attempt to create a new canary release.
Dependabot PRs need to be reviewed anyways and there is no need that a canary deployment is attempted, as it will fail anyways.
<details>
<summary>📦 Published PR as canary version: <code>20.54.0--canary.1042.f17485f37762ce1f810a1a7c0ea85ee186c59fb5.0</code></summar …
=> 1041 enhancement skip canary release creation when workflow is triggered by dependabot secrets not accessible

packages/components/src/components/progress-bar/progress-bar.tsx
Description
Fixed the tagged issue by:
1) Hiding text when value is 0
2) Filling progress by 2% when value is 1 to avoid text overflow.
Related Issue
#1012 
<details>
<summary>📦 Published PR as canary version: <code>20.57.2--canary.1121.5ffabe97bbdb767c0fa69c578516c9b80247fb92.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.57.2--canary.1121.5ffabe97bbdb767c0fa69c578516c9b80247fb92.0
yarn add @infineon/infineon-design-system-stencil@20.57.2--canary.1121.5ffabe97bb …
```
=> Progress bar: fixed bug where label text looked broken

lerna.json, package-lock.json, packages/components-angular/package.json, packages/components-angular/projects/component-library/package.json, packages/components-react/package.json, packages/components-vue/package.json, packages/components/package.json, packages/components/src/components/accordion/accordion.stories.tsx, packages/components/src/components/accordion/accordionItem.tsx, packages/components/src/components/accordion/readme.md
Removed `initialCollapse` prop from `accordionItem` as it was redundant. 
<details>
<summary>📦 Published PR as canary version: <code>25.6.0--canary.1517.a14961e3135f4f26e2068de0965d7636ecc8f737.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@25.6.0--canary.1517.a14961e3135f4f26e2068de0965d7636ecc8f737.0
yarn add @infineon/infineon-design-system-stencil@25.6.0--canary.1517.a14961e3135f4f26e2068de0965d7636ecc8f737.0
```
</details>
=> Accordion: Removed redundant code

lerna.json, package-lock.json, packages/components-angular/package.json, packages/components-angular/projects/component-library/package.json, packages/components-react/package.json, packages/components-vue/package.json, packages/components/package.json, packages/components/src/components/icon-button/icon-button.e2e.ts, packages/components/src/components/icon-button/icon-button.tsx, packages/components/src/index.html
When disable is true, the onClick event is not emitted anymore on click.
Relevant issue: https://github.com/Infineon/infineon-design-system-stencil/issues/1488
<details>
<summary>📦 Published PR as canary version: <code>25.6.3--canary.1519.3d42092a7be308839d7d98a7fc1396d2c67edc8b.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@25.6.3--canary.1519.3d42092a7be308839d7d98a7fc1396d2c67edc8b.0
yarn add @infineon/infineon-design-system-stencil@25.6.3--canary.1519.3d42092a7be308839d7d98a7fc1396d2c67edc8b.0
```
</details>
=> Icon-button: event not emitted anymore when disabled

examples/wrapper-components/react-vite-js/package.json, examples/wrapper-components/vue-javascript/package.json, lerna.json, package-lock.json, packages/components-angular/package.json, packages/components-angular/projects/component-library/package.json, packages/components-react/package.json, packages/components-vue/package.json, packages/components/package.json, packages/components/src/components/select/multi-select/multiselect.tsx
Description
The placeholder property in the multiselect component was fixed. Now it uses the value from the property to display its content. Before, it was using a hardcoded string with the value "Placeholder".
Related Issue
#1424 
<details>
<summary>📦 Published PR as canary version: <code>25.15.1--canary.1558.b04c1697c98fe53f8d029696d6c1a4aafe099229.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@25.15.1--canary.1558.b04c1697c98fe53f8d029696d6c1a4aafe099229.0
yarn …
```
=> Bugfix: Placeholder in Multiselect is now changeable 

examples/wrapper-components/react-vite-js/package.json, examples/wrapper-components/vue-javascript/package.json, lerna.json, package-lock.json, packages/components-angular/package.json, packages/components-angular/projects/component-library/package.json, packages/components-react/package.json, packages/components-vue/package.json, packages/components/package.json, packages/components/src/components/navigation/navbar/navbar-item.scss
Description
Navbar menu now has no max height and will display all items at once.
Related Issue
#1548
Context
<details>
<summary>📦 Published PR as canary version: <code>25.17.1--canary.1564.3f949f032ad1ef5384e3224642054812c6d2794d.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@25.17.1--canary.1564.3f949f032ad1ef5384e3224642054812c6d2794d.0
yarn add @infineon/infineon-design-system-stencil@25.17.1--canary.1564.3f949f032ad1ef5384e3224642054812c6d2794d.0
``` …
=> Navbar-item: removed max-height

examples/wrapper-components/react-vite-js/package.json, examples/wrapper-components/vue-javascript/package.json, lerna.json, package-lock.json, packages/components-angular/package.json, packages/components-angular/projects/component-library/package.json, packages/components-react/package.json, packages/components-vue/package.json, packages/components/package.json, packages/components/src/components/slider/slider.tsx
Description
Ensured that the last used slider thumb stays on top of the other thumb in order to handle correct overlapping 
if min and max thumbs take the same value.
Related Issue
#1539
<details>
<summary>📦 Published PR as canary version: <code>25.18.1--canary.1567.6510a80557e0611c0b0130ba9658379ed51eab31.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@25.18.1--canary.1567.6510a80557e0611c0b0130ba9658379ed51eab31.0
yarn add …
```
=> Slider: set higher z-index on last active handle to prevent double click when both handles overlap

examples/stencil-components/vanilla-cdn/index.html, examples/stencil-components/vanilla-cdn/package.json, examples/stencil-components/vanilla-cdn/readme.md, examples/stencil-components/vanilla-cdn/update-link.js, examples/stencil-components/vanilla-cdn/vite.config.js, examples/wrapper-components/react-vite-js/package-lock.json, examples/wrapper-components/react-vite-js/package.json, examples/wrapper-components/vue-javascript/package.json, lerna.json, package-lock.json, packages/components-angular/package.json, packages/components-angular/projects/component-library/package.json, packages/components-react/package.json, packages/components-vue/package.json, packages/components/package.json
Description
Use canary release of Tokens package to consume fonts from CDN
<details>
<summary>📦 Published PR as canary version: <code>27.10.2--canary.1561.333cd73f994eeebe23606e192659070c1e9b6a73.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@27.10.2--canary.1561.333cd73f994eeebe23606e192659070c1e9b6a73.0
yarn add @infineon/infineon-design-system-stencil@27.10.2--canary.1561.333cd73f994eeebe23606e192659070c1e9b6a73.0
```
</details>
=> Bugfix: Use canary release of Tokens package to consume fonts from CDN

examples/wrapper-components/react-vite-js/package.json, examples/wrapper-components/vue-javascript/package.json, lerna.json, package-lock.json, packages/components-angular/package.json, packages/components-angular/projects/component-library/package.json, packages/components-react/package.json, packages/components-vue/package.json, packages/components/package.json, packages/components/src/components/icon-button/icon-button.stories.ts, packages/components/src/components/icon-button/icon-button.tsx, packages/components/src/components/icon-button/readme.md
Description
Added area-label and area-disabled to IconButton to enhance accessibility.
Related Issue
#1264
Context
Accessibility enhancement 
<details>
<summary>📦 Published PR as canary version: <code>33.1.4--canary.1826.df088e460080752b9ce982492f593644b897818c.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@33.1.4--canary.1826.df088e460080752b9ce982492f593644b897818c.0
yarn add @infineon/infineon-design-system-stencil@33.1.4--canary.1826.df088e460080752b9ce982492f59 …
```
=> Accessibility enhancement added to IconButton
