- src/components/dropdown/dropdown.tsx
- src/index.html
Description
Merge new dropdown feature changes into master
<details>
<summary>📦 Published PR as canary version: <code>0.0.32--canary.5.165d5d33fb47b52dcc4440d4166dad76c4ec4f5d.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@0.0.32--canary.5.165d5d33fb47b52dcc4440d4166dad76c4ec4f5d.0
yarn add @infineon/infineon-design-system-stencil@0.0.32--canary.5.165d5d33fb47b52dcc4440d4166dad76c4ec4f5d.0
```
</details>
> dropdown with slot

- README.md
Updated the readme
New readme for the additional steps needed for Angular
<details>
<summary>📦 Published PR as canary version: <code>0.0.41--canary.8.cee4fea4cce770e8a7787da0d93cfcbee261a956.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@0.0.41--canary.8.cee4fea4cce770e8a7787da0d93cfcbee261a956.0
yarn add @infineon/infineon-design-system-stencil@0.0.41--canary.8.cee4fea4cce770e8a7787da0d93cfcbee261a956.0
```
</details>
> new readme for angular

- README.md
- package-lock.json
- package.json
- stencil.config.ts
Updated readme, removed nodePolyfills package cause not needed
<details>
<summary>📦 Published PR as canary version: <code>0.0.47--canary.11.64d070d5582a3efdd5f9f3cadec25809477c3195.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@0.0.47--canary.11.64d070d5582a3efdd5f9f3cadec25809477c3195.0
yarn add @infineon/infineon-design-system-stencil@0.0.47--canary.11.64d070d5582a3efdd5f9f3cadec25809477c3195.0
```
</details>
> removed nodePolyfills package, updated readme

- src/components/dropdown/dropdown.stories.ts
- src/components/dropdown/dropdown.tsx
- src/global/global-theme.scss
- src/index.html
Fixed the global sizing
<details>
<summary>📦 Published PR as canary version: <code>0.0.52--canary.16.7c15041194dac5585381365daff28245393bc72a.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@0.0.52--canary.16.7c15041194dac5585381365daff28245393bc72a.0
yarn add @infineon/infineon-design-system-stencil@0.0.52--canary.16.7c15041194dac5585381365daff28245393bc72a.0
```
</details>
> fixed sizes

- src/components/dropdown/dropdown.tsx
- src/index.html
dropdown menu closes when another one opens.
<details>
<summary>📦 Published PR as canary version: <code>0.0.64--canary.24.edc5f06e007c88c02b07dbfcf0e73dbec42f1e08.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@0.0.64--canary.24.edc5f06e007c88c02b07dbfcf0e73dbec42f1e08.0
yarn add @infineon/infineon-design-system-stencil@0.0.64--canary.24.edc5f06e007c88c02b07dbfcf0e73dbec42f1e08.0
```
</details>
> outside click closes menu

- src/components/dropdown-item/dropdown-item.scss
- src/components/dropdown-item/dropdown-item.tsx
- src/components/dropdown-menu/dropdown-menu.scss
- src/components/dropdown/dropdown.tsx
- src/index.html
dropdown adjusted to the latest figma design
<details>
<summary>📦 Published PR as canary version: <code>0.0.64--canary.25.ba5d4bc658039ee3e0a7788b87c8a0dcc9020fbb.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@0.0.64--canary.25.ba5d4bc658039ee3e0a7788b87c8a0dcc9020fbb.0
yarn add @infineon/infineon-design-system-stencil@0.0.64--canary.25.ba5d4bc658039ee3e0a7788b87c8a0dcc9020fbb.0
```
</details>
> latest figma design

- src/components.d.ts
- src/components/alert/_alert.scss
- src/components/alert/alert.stories.ts
- src/components/alert/alert.tsx
- src/components/alert/readme.md
- src/index.html
Alert component
<details>
<summary>📦 Published PR as canary version: <code>0.0.64--canary.27.2fbbc04ed322b98f33fe62ff065779255083f074.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@0.0.64--canary.27.2fbbc04ed322b98f33fe62ff065779255083f074.0
yarn add @infineon/infineon-design-system-stencil@0.0.64--canary.27.2fbbc04ed322b98f33fe62ff065779255083f074.0
```
</details>
> new alert component

- src/components.d.ts
- src/components/dropdown-menu/dropdown-menu.scss
- src/components/dropdown/dropdown.stories.ts
- src/components/dropdown/dropdown.tsx
- src/components/search-input/readme.md
- src/components/search-input/search-input.scss
- src/components/search-input/search-input.tsx
- src/index.html
- src/index.scss
Renamed ifx-dropdown-search to ifx-search-input
<details>
<summary>📦 Published PR as canary version: <code>0.0.64--canary.28.23f8dfa144dbeaf5aef9772d8884bbacff22c5b0.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@0.0.64--canary.28.23f8dfa144dbeaf5aef9772d8884bbacff22c5b0.0
yarn add @infineon/infineon-design-system-stencil@0.0.64--canary.28.23f8dfa144dbeaf5aef9772d8884bbacff22c5b0.0
```
</details>
> renamed dropdown-search

- src/components/button/_button.scss
- src/components/button/button.tsx
- src/index.html
Re-adjusted the classes of the button component
<details>
<summary>📦 Published PR as canary version: <code>0.0.64--canary.32.ec712944d872095e6c7c7e614ce456a5f1f55fef.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@0.0.64--canary.32.ec712944d872095e6c7c7e614ce456a5f1f55fef.0
yarn add @infineon/infineon-design-system-stencil@0.0.64--canary.32.ec712944d872095e6c7c7e614ce456a5f1f55fef.0
```
</details>
> re-organized the classes

- src/components/button/button.tsx
- src/index.html
Made default variant be solid
<details>
<summary>📦 Published PR as canary version: <code>0.0.64--canary.34.fe246e0e93291c0ccbd09cc898655b6a68deee05.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@0.0.64--canary.34.fe246e0e93291c0ccbd09cc898655b6a68deee05.0
yarn add @infineon/infineon-design-system-stencil@0.0.64--canary.34.fe246e0e93291c0ccbd09cc898655b6a68deee05.0
```
</details>
> default variant

- src/components/dropdown/dropdown.tsx
- src/index.html
When dropdown button is disabled, dropdown-menu does not open.
<details>
<summary>📦 Published PR as canary version: <code>0.0.64--canary.36.71ad21c776689f68b340e038027c6ea2bd44f3b5.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@0.0.64--canary.36.71ad21c776689f68b340e038027c6ea2bd44f3b5.0
yarn add @infineon/infineon-design-system-stencil@0.0.64--canary.36.71ad21c776689f68b340e038027c6ea2bd44f3b5.0
```
</details>
> disabled dropdown-menu

- src/components/dropdown-item/dropdown-item.tsx
- src/components/dropdown-menu/dropdown-menu.tsx
- src/index.html
Changed componentDidRender to componentWillRender in order to prevent potential infinite loop.
> removed warnings to potential errors

- src/components/dropdown-item/dropdown-item.scss
- src/components/dropdown-item/dropdown-item.tsx
- src/components/dropdown/dropdown.stories.ts
- src/components/dropdown/dropdown.tsx
- src/index.html
- Fixed storybook error when you click on dropdown filter or search inputs
- Fixed dropdown-item label not remaining colored if icon exist
- Fixed dropdown-icon checkbox not getting checked if click on icon
- Fixed dropdown-item label not getting checked if click outside of label
- Added dropdown-item icon variant to storybook
<details>
<summary>📦 Published PR as canary version: <code>0.0.64--canary.43.8a840b7b8bb80b0838da942973dddefbc3e2cbd6.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@0.0.64--canary.43.8a840b7b8bb80b0838da942 …
```
> fixed dropdown related issues

- src/components.d.ts
- src/components/button/button.tsx
- src/components/card-headline/card-headline.scss
- src/components/card-headline/card-headline.tsx
- src/components/card-headline/readme.md
- src/components/card-overline/card-overline.scss
- src/components/card-overline/card-overline.tsx
- src/components/card-overline/readme.md
- src/components/card-text/card-text.scss
- src/components/card-text/card-text.tsx
- src/components/card-text/readme.md
- src/components/card/_card.scss
- src/components/card/card.stories.ts
- src/components/card/card.tsx
- src/components/card/readme.md
- src/components/icon-button/icon-button.stories.ts
- src/components/icon/readme.md
- src/components/link/ifx-link.scss
- src/components/link/ifx-link.stories.ts
- src/components/link/ifx-link.tsx
- src/components/link/readme.md
- src/index.html
- src/index.scss
Updated the Card component to match Figma and latest standards.
<details>
<summary>📦 Published PR as canary version: <code>0.0.64--canary.49.2f7ee5f8dc91d0e275ff8b8a348ff7d5210d281e.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@0.0.64--canary.49.2f7ee5f8dc91d0e275ff8b8a348ff7d5210d281e.0
yarn add @infineon/infineon-design-system-stencil@0.0.64--canary.49.2f7ee5f8dc91d0e275ff8b8a348ff7d5210d281e.0
```
</details>
> completed card component

- src/components.d.ts
- src/components/button/button.tsx
- src/components/button/readme.md
- src/components/ifxModal/ifxModal.e2e.tsx
- src/components/ifxModal/ifxModal.scss
- src/components/ifxModal/ifxModal.stories.ts
- src/components/ifxModal/ifxModal.tsx
- src/components/ifxModal/readme.md
added modal + alert components
> Added Modal + Alert components

- src/components.d.ts
- src/components/ifxAccordion/ifxAccordion.e2e.tsx
- src/components/ifxAccordion/ifxAccordion.scss
- src/components/ifxAccordion/ifxAccordion.stories.tsx
- src/components/ifxAccordion/ifxAccordion.tsx
- src/components/ifxAccordion/ifxAccordionItem.scss
- src/components/ifxAccordion/ifxAccordionItem.tsx
- src/components/ifxAccordion/readme.md
added accordion component based on figma design
> added accordion component

- src/components.d.ts
- src/components/icon/readme.md
- src/components/ifxRange/ifxRange.e2e.tsx
- src/components/ifxRange/ifxRange.scss
- src/components/ifxRange/ifxRange.stories.tsx
- src/components/ifxRange/ifxRange.tsx
- src/components/ifxRange/readme.md
added range component based on figma design
> added range component

- .github/workflows/shipit_master.yml
- .github/workflows/shipit_pr.yml
- src/components.d.ts
- src/components/icon/readme.md
- src/components/ifxToggle/ifxToggle.e2e.tsx
- src/components/list-group/list-group-notification.tsx
- src/components/list-group/readme.md
- src/components/radio-button/radio-button.scss
- src/components/radio-button/radio-button.stories.ts
- src/components/radio-button/radio-button.tsx
- src/components/radio-button/readme.md
- src/components/tabs/tabs.stories.tsx
- src/index.html
The Radio Button Component
<details>
<summary>📦 Published PR as canary version: <code>18.0.9--canary.126.43b932f04a6bd5f6a1b3d648b67507502eeaad10.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@18.0.9--canary.126.43b932f04a6bd5f6a1b3d648b67507502eeaad10.0
yarn add @infineon/infineon-design-system-stencil@18.0.9--canary.126.43b932f04a6bd5f6a1b3d648b67507502eeaad10.0
```
</details>
> 125 radio button

- .storybook/preview.js
- package-lock.json
- package.json
- src/components.d.ts
- src/components/icon/infineonIconStencil.stories.ts
- src/components/icon/readme.md
- src/components/icons-preview/icons-preview.scss
- src/components/icons-preview/icons-preview.stories.ts
- src/components/icons-preview/icons-preview.tsx
- src/components/icons-preview/readme.md
- src/components/tabs/tabs.stories.tsx
- src/index.html
- src/stories/About.stories.mdx
- src/stories/About.stories.ts
- src/stories/About_en.md
- src/stories/Custom-MDX-Documentation.mdx
- src/stories/icons-preview.stories.ts
- src/stories/setup/GettingStarted.stories.mdx
- src/stories/setup/GettingStarted_en.md
Description
Added some general markdown pages, outside of the component section
<details>
<summary>📦 Published PR as canary version: <code>18.0.12--canary.121.2996def4f7b725b8b8185dc1476361e5955435ae.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@18.0.12--canary.121.2996def4f7b725b8b8185dc1476361e5955435ae.0
yarn add @infineon/infineon-design-system-stencil@18.0.12--canary.121.2996def4f7b725b8b8185dc1476361e5955435ae.0
```
</details>
> About and getting started page added

- src/components/dropdown/dropdown.scss
- src/index.html
navbar fixed issues
<details>
<summary>📦 Published PR as canary version: <code>18.0.14--canary.129.67268bd003e80ec9923e3f7396ee2dc8474d6da9.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@18.0.14--canary.129.67268bd003e80ec9923e3f7396ee2dc8474d6da9.0
yarn add @infineon/infineon-design-system-stencil@18.0.14--canary.129.67268bd003e80ec9923e3f7396ee2dc8474d6da9.0
```
</details>
> new commit

- src/components/select-input/select-input.stories.ts
fixed select input component
<details>
<summary>📦 Published PR as canary version: <code>18.0.20--canary.147.652917a752b5af7a3e7c02c54ddcc3a8fb9029d5.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@18.0.20--canary.147.652917a752b5af7a3e7c02c54ddcc3a8fb9029d5.0
yarn add @infineon/infineon-design-system-stencil@18.0.20--canary.147.652917a752b5af7a3e7c02c54ddcc3a8fb9029d5.0
```
</details>
> working commit

- src/components/multi-select-input/multi-select-input.scss
- src/components/multi-select-input/multi-select-input.tsx
- src/components/text-input/text-input.scss
- src/index.html
Fixed the dropdown class being overwritten 
<details>
<summary>📦 Published PR as canary version: <code>18.0.21--canary.148.f9de78887c4b7b8cb7157793fbaa02d7345c99d7.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@18.0.21--canary.148.f9de78887c4b7b8cb7157793fbaa02d7345c99d7.0
yarn add @infineon/infineon-design-system-stencil@18.0.21--canary.148.f9de78887c4b7b8cb7157793fbaa02d7345c99d7.0
```
</details>
> fixed select input class

- examples/wrapper-components/react-javascript/package-lock.json
- examples/wrapper-components/react-javascript/src/App.js
- packages/components-vue/lib/components.ts
- packages/components/src/components/alert/alert.scss
- packages/components/src/components/alert/alert.tsx
- packages/components/src/components/alert/readme.md
- Added event when close (X) button is clicked
- Optimized the scss file for consistency and better use
<details>
<summary>📦 Published PR as canary version: <code>18.2.2--canary.194.9664b1ed0925507f45bb95a51f67478d922274a8.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@18.2.2--canary.194.9664b1ed0925507f45bb95a51f67478d922274a8.0
yarn add @infineon/infineon-design-system-stencil@18.2.2--canary.194.9664b1ed0925507f45bb95a51f67478d922274a8.0
```
</details>
> Alert close event

- examples/stencil-components/vanilla-cdn/index.html
- examples/wrapper-components/react-javascript/src/App.js
- examples/wrapper-components/react-javascript/src/components/ProgressBar/ProgressBar.js
- examples/wrapper-components/vue-javascript/src/App.vue
- examples/wrapper-components/vue-javascript/src/components/ProgressBar.vue
- examples/wrapper-components/vue-typescript/src/components/ProgressBar.vue
- packages/components-vue/lib/components.ts
- packages/components/framework-output-targets.ts
- packages/components/src/components/progress-bar/progress-bar.e2e.ts
- packages/components/src/components/progress-bar/progress-bar.scss
- packages/components/src/components/progress-bar/progress-bar.stories.ts
- packages/components/src/components/progress-bar/progress-bar.tsx
- packages/components/src/components/progress-bar/progress-bar_usage.md
- packages/components/src/components/progress-bar/readme.md
- packages/components/src/index.html
Description
added e2e tests
removed ifxChange event, cause it doesnt need to emit an event, (discussed with Kai in one of our latest review sessions)
added to example apps
<details>
<summary>📦 Published PR as canary version: <code>18.2.6--canary.203.538df711774c3016a7f068860f87b3a23fb9f85a.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@18.2.6--canary.203.538df711774c3016a7f068860f87b3a23fb9f85a.0
yarn add @infineon/infineon-design-system-stencil@18.2.6--canary.203.5 …
```
> 186 review progress bar

- examples/wrapper-components/vue-javascript/src/components/Button.vue
- examples/wrapper-components/vue-typescript/src/components/Button.vue
- packages/components-vue/lib/components.ts
- packages/components/src/components/breadcrumb/readme.md
- packages/components/src/components/button/button.scss
- packages/components/src/components/button/button.stories.ts
- packages/components/src/components/button/button.tsx
- packages/components/src/components/button/readme.md
- packages/components/src/components/icon/infineonIconStencil.scss
- packages/components/src/components/icon/readme.md
- packages/components/src/components/list-group/readme.md
- packages/components/src/components/modal/readme.md
- packages/components/src/components/navbar/readme.md
- packages/components/src/components/tabs/readme.md
- packages/components/src/index.html
- removed the button element
- made the anchor work for all 3 user-cases: inside form, as link and as type button. Now the new button with type submit triggered by the anchor just like it was triggered by the normal button before.
- removed the imbedded icon and its relevant code, and replaced it with a slotted one.
- removed min-width from default and small size
- replaced the min-height with a fixed height (as is shown in Figma)
- removed unneeded Props
- Added internal href State for internal use
- added :empty pseudo-class with display none to the icon component so that the icon is not rendered if name …
> 340 update the button component

- packages/components/src/components/badge/Usage.mdx
- changed image width in Usage.mdx of Badge
<details>
<summary>📦 Published PR as canary version: <code>20.2.1--canary.376.83680f58eca8c7a1bea0bf0455f512ec5454240c.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.2.1--canary.376.83680f58eca8c7a1bea0bf0455f512ec5454240c.0
yarn add @infineon/infineon-design-system-stencil@20.2.1--canary.376.83680f58eca8c7a1bea0bf0455f512ec5454240c.0
```
</details>
> Documentation: badge update

- packages/components/src/components/checkbox/Usage.mdx
<details>
<summary>📦 Published PR as canary version: <code>20.6.1--canary.408.dfab22481eac7632d1fc7124b5eaf74379c650be.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.6.1--canary.408.dfab22481eac7632d1fc7124b5eaf74379c650be.0
yarn add @infineon/infineon-design-system-stencil@20.6.1--canary.408.dfab22481eac7632d1fc7124b5eaf74379c650be.0
```
</details>
> Documentation: checkbox update

- packages/components/src/components/button/Usage.mdx
<details>
<summary>📦 Published PR as canary version: <code>20.7.1--canary.410.ea02215fdcabc748d2fd822b8024e4967394cac8.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.7.1--canary.410.ea02215fdcabc748d2fd822b8024e4967394cac8.0
yarn add @infineon/infineon-design-system-stencil@20.7.1--canary.410.ea02215fdcabc748d2fd822b8024e4967394cac8.0
```
</details>
> Documentation: button update

- packages/components/src/components/chips/chip.e2e.ts
Description
e2e tests added
<details>
<summary>📦 Published PR as canary version: <code>20.9.2--canary.415.916948a96ff6bc69893d87d7256d625d5229d470.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.9.2--canary.415.916948a96ff6bc69893d87d7256d625d5229d470.0
yarn add @infineon/infineon-design-system-stencil@20.9.2--canary.415.916948a96ff6bc69893d87d7256d625d5229d470.0
```
</details>
> e2e tests added for chip component

- examples/stencil-components/vanilla-cdn/index.html
- examples/wrapper-components/vue-javascript/src/components/SingleSelect.vue
- packages/components/src/components/select/select.tsx
Description
no longer querying the document itself, using root
<details>
<summary>📦 Published PR as canary version: <code>20.10.0--canary.420.3eba787353819afbb6ac5d67e682f36bfe8caf55.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.10.0--canary.420.3eba787353819afbb6ac5d67e682f36bfe8caf55.0
yarn add @infineon/infineon-design-system-stencil@20.10.0--canary.420.3eba787353819afbb6ac5d67e682f36bfe8caf55.0
```
</details>
> Code quality: Single-select - replaced document with this.root to not query the document

- packages/components/src/components/modal/Usage.mdx
- changed documneation in usage.mdx
<details>
<summary>📦 Published PR as canary version: <code>20.11.2--canary.428.755817668747c4e1ab998917b36c6d53cacb2467.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.11.2--canary.428.755817668747c4e1ab998917b36c6d53cacb2467.0
yarn add @infineon/infineon-design-system-stencil@20.11.2--canary.428.755817668747c4e1ab998917b36c6d53cacb2467.0
```
</details>
> Documentation: modal update

- packages/components/src/components/link/Usage.mdx
<details>
<summary>📦 Published PR as canary version: <code>20.12.1--canary.431.772d36329903b2fd438ef63ed699329df73da423.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.12.1--canary.431.772d36329903b2fd438ef63ed699329df73da423.0
yarn add @infineon/infineon-design-system-stencil@20.12.1--canary.431.772d36329903b2fd438ef63ed699329df73da423.0
```
</details>
> Documentation: link update

- packages/components/src/components/tag/Usage.mdx
<details>
<summary>📦 Published PR as canary version: <code>20.12.1--canary.433.21414a202aa191d060eca1f2609e2d90214e79db.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.12.1--canary.433.21414a202aa191d060eca1f2609e2d90214e79db.0
yarn add @infineon/infineon-design-system-stencil@20.12.1--canary.433.21414a202aa191d060eca1f2609e2d90214e79db.0
```
</details>
> Documentation: tag update

- packages/components/src/components/navbar/Usage.mdx
- deleted image in usage.mdx
<details>
<summary>📦 Published PR as canary version: <code>20.16.8--canary.485.87d55d28d5ea98fe0a32bc1bca3e866aa297e038.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.16.8--canary.485.87d55d28d5ea98fe0a32bc1bca3e866aa297e038.0
yarn add @infineon/infineon-design-system-stencil@20.16.8--canary.485.87d55d28d5ea98fe0a32bc1bca3e866aa297e038.0
```
</details>
> Documentation: navbar update

- packages/components/src/components/checkbox/Usage.mdx
- packages/components/src/components/radio-button/Usage.mdx
- packages/components/src/components/slider/Usage.mdx
- packages/components/src/components/switch/Usage.mdx
- packages/components/src/components/text-field/Usage.mdx
- changed bottom figma-url-text in usage.mdx of components:
checkbox, radio-button, switch, text-field, slider
<details>
<summary>📦 Published PR as canary version: <code>20.16.7--canary.478.22823e4130f336e35f1352af0adfa80175bcc5e0.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.16.7--canary.478.22823e4130f336e35f1352af0adfa80175bcc5e0.0
yarn add @infineon/infineon-design-system-stencil@20.16.7--canary.478.22823e4130f336e35f1352af0adfa80175bcc5e0.0
```
</details>
> Documentation: content update

- packages/components/src/components/radio-button/radio-button.e2e.ts
- packages/components/src/components/radio-button/radio-button.scss
- packages/components/src/components/radio-button/radio-button.tsx
- packages/components/src/index.html
Description
radio-button design review changes implemented
<details>
<summary>📦 Published PR as canary version: <code>20.17.2--canary.492.d0722b1f10214396bb1e39c90f46c2886dd90038.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.17.2--canary.492.d0722b1f10214396bb1e39c90f46c2886dd90038.0
yarn add @infineon/infineon-design-system-stencil@20.17.2--canary.492.d0722b1f10214396bb1e39c90f46c2886dd90038.0
```
</details>
> radio-button design review updates

- packages/components-vue/lib/components.ts
- packages/components/src/components/checkbox/checkbox.scss
- packages/components/src/components/checkbox/checkbox.stories.ts
- packages/components/src/components/checkbox/checkbox.tsx
- packages/components/src/components/checkbox/readme.md
- packages/components/src/components/select/multi-select/multiselect.stories.ts
- packages/components/src/components/select/single-select/select.stories.ts
Description
checkbox design review issues resolved
<details>
<summary>📦 Published PR as canary version: <code>20.17.1--canary.491.c6e3437e0502f6ef9c92da5fa2d6c07133f564d1.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.17.1--canary.491.c6e3437e0502f6ef9c92da5fa2d6c07133f564d1.0
yarn add @infineon/infineon-design-system-stencil@20.17.1--canary.491.c6e3437e0502f6ef9c92da5fa2d6c07133f564d1.0
```
</details>
> checkbox sizes added;font changed;error state fix

- package-lock.json
- packages/components/src/components/alert/alert.e2e.ts
- packages/components/src/components/alert/alert.scss
- packages/components/src/components/alert/alert.stories.ts
- packages/components/src/components/alert/alert.tsx
- packages/components/src/components/alert/readme.md
Issue 1: The height was already 48px. Furthermore, the height is not fixed. It is adjusted to content. Height in Figma is not fixed either. 
Issue 2: Removed the 'success' color variant.
Issue 3: Left for version 2.
<details>
<summary>📦 Published PR as canary version: <code>20.18.0--canary.498.c0079b2faebef6009d9dd7f947fb10b48c50bcdb.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.18.0--canary.498.c0079b2faebef6009d9dd7f947fb10b48c50bcdb.0
yarn add @infineon/infineon-design-system-stencil@20.18.0--canary.498.c0079b2faebef6009d9 …
```
> Alert: updated in accordance to design review

- packages/components/src/components/breadcrumb/breadcrumb-item.scss
Changed divider border from tokens.$ifxColorEngineering300 to tokens.$ifxColorEngineering200
<details>
<summary>📦 Published PR as canary version: <code>20.17.6--canary.500.bad6e1ad37e960cd17343c5be625aabb226c27ef.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.17.6--canary.500.bad6e1ad37e960cd17343c5be625aabb226c27ef.0
yarn add @infineon/infineon-design-system-stencil@20.17.6--canary.500.bad6e1ad37e960cd17343c5be625aabb226c27ef.0
```
</details>
> Breadcrumb: updated in accordance with design review

- packages/components/src/components/breadcrumb/breadcrumb-item-label.scss
- packages/components/src/components/breadcrumb/breadcrumb-item.scss
- packages/components/src/components/breadcrumb/breadcrumb.scss
- packages/components/src/components/sidebar/sidebar-item.scss
- packages/components/src/components/sidebar/sidebar.scss
- packages/components/src/index.html
Added the correct font-family. 
<details>
<summary>📦 Published PR as canary version: <code>20.17.6--canary.503.8928915e049ebad49f60a46106a92fd0cc569bf5.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.17.6--canary.503.8928915e049ebad49f60a46106a92fd0cc569bf5.0
yarn add @infineon/infineon-design-system-stencil@20.17.6--canary.503.8928915e049ebad49f60a46106a92fd0cc569bf5.0
```
</details>
> Sidebar: updated in accordance with design review

- packages/components/src/components/status/readme.md
- packages/components/src/components/status/status.scss
- packages/components/src/components/status/status.stories.ts
- packages/components/src/components/status/status.tsx
Description
Issues from Design review resolved
<details>
<summary>📦 Published PR as canary version: <code>20.19.1--canary.505.5d56fcae54636ff5e04c665f090f8c36a3797639.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.19.1--canary.505.5d56fcae54636ff5e04c665f090f8c36a3797639.0
yarn add @infineon/infineon-design-system-stencil@20.19.1--canary.505.5d56fcae54636ff5e04c665f090f8c36a3797639.0
```
</details>
> design review changes: status

- packages/components-vue/lib/components.ts
- packages/components/src/components/search-bar/readme.md
- packages/components/src/components/search-bar/search-bar.stories.ts
- packages/components/src/components/search-bar/search-bar.tsx
Description
design review changes implemented
<details>
<summary>📦 Published PR as canary version: <code>20.19.1--canary.507.516f768a6663db82ecc46626c306bdc5d4df1d4f.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.19.1--canary.507.516f768a6663db82ecc46626c306bdc5d4df1d4f.0
yarn add @infineon/infineon-design-system-stencil@20.19.1--canary.507.516f768a6663db82ecc46626c306bdc5d4df1d4f.0
```
</details>
> search-bar design review updates implemented

- packages/components/src/components/switch/switch.scss
- packages/components/src/components/switch/switch.stories.ts
- packages/components/src/components/switch/switch.tsx
Description
switch design update
<details>
<summary>📦 Published PR as canary version: <code>20.19.4--canary.512.5daaacfe11bdf64ac17d09c4c0a5ec7fd14112b2.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.19.4--canary.512.5daaacfe11bdf64ac17d09c4c0a5ec7fd14112b2.0
yarn add @infineon/infineon-design-system-stencil@20.19.4--canary.512.5daaacfe11bdf64ac17d09c4c0a5ec7fd14112b2.0
```
</details>
> Design review changes: Switch

- packages/components/src/components/button/button.stories.ts
- packages/components/src/components/icon-button/icon-button.stories.ts
- packages/components/src/components/slider/slider.scss
- packages/components/src/components/slider/slider.tsx
- packages/components/src/index.html
Description
design review changes implemented
<details>
<summary>📦 Published PR as canary version: <code>20.19.5--canary.510.ad6d48c62ea7b2f8ad83a5da0fb853cf1e11c064.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.19.5--canary.510.ad6d48c62ea7b2f8ad83a5da0fb853cf1e11c064.0
yarn add @infineon/infineon-design-system-stencil@20.19.5--canary.510.ad6d48c62ea7b2f8ad83a5da0fb853cf1e11c064.0
```
</details>
> design review changes: slider

- packages/components/src/components/progress-bar/progress-bar.stories.ts
Description
design review change implemented
<details>
<summary>📦 Published PR as canary version: <code>20.19.6--canary.509.3f4e128eabf4482c6bdc54ed88cc1e86338c4347.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.19.6--canary.509.3f4e128eabf4482c6bdc54ed88cc1e86338c4347.0
yarn add @infineon/infineon-design-system-stencil@20.19.6--canary.509.3f4e128eabf4482c6bdc54ed88cc1e86338c4347.0
```
</details>
> design review change: progress-bar

- packages/components/src/components/search-field/search-field.scss
- packages/components/src/components/search-field/search-field.stories.ts
- packages/components/src/components/search-field/search-field.tsx
- packages/components/src/index.html
Description
design review changes implemented
<details>
<summary>📦 Published PR as canary version: <code>20.19.4--canary.508.645d10f4dba7142814e2abadbd1a099e9bcfa4af.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.19.4--canary.508.645d10f4dba7142814e2abadbd1a099e9bcfa4af.0
yarn add @infineon/infineon-design-system-stencil@20.19.4--canary.508.645d10f4dba7142814e2abadbd1a099e9bcfa4af.0
```
</details>
> design review changes: search field

- packages/components/src/components/footer/Usage.mdx
- deleted text and image in usage.mdx
<details>
<summary>📦 Published PR as canary version: <code>20.19.4--canary.516.0a232f459de217f26c84ac817a2b7d453fbfff4c.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.19.4--canary.516.0a232f459de217f26c84ac817a2b7d453fbfff4c.0
yarn add @infineon/infineon-design-system-stencil@20.19.4--canary.516.0a232f459de217f26c84ac817a2b7d453fbfff4c.0
```
</details>
> Documentation: footer update

- examples/stencil-components/angular/src/app/app.component.html
- examples/stencil-components/vanilla-cdn/index.html
- package-lock.json
- packages/components/src/components/accordion/accordion.stories.tsx
- packages/components/src/components/accordion/accordion.tsx
- packages/components/src/components/accordion/accordionItem.scss
- packages/components/src/components/icon-button/icon-button.tsx
- packages/components/src/components/icon-button/readme.md
- packages/components/src/components/pagination/pagination.tsx
- packages/components/src/index.html
Description
accordion design changes implemented
<details>
<summary>📦 Published PR as canary version: <code>20.21.2--canary.521.7fce8094eafa5598117b7f1b7bdfc91d5e8dff3a.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.21.2--canary.521.7fce8094eafa5598117b7f1b7bdfc91d5e8dff3a.0
yarn add @infineon/infineon-design-system-stencil@20.21.2--canary.521.7fce8094eafa5598117b7f1b7bdfc91d5e8dff3a.0
```
</details>
> accordion design changes implemented

- packages/components-vue/lib/components.ts
- packages/components/src/components/link/link.scss
- packages/components/src/components/link/link.stories.ts
- packages/components/src/components/link/link.tsx
- packages/components/src/components/link/readme.md
- Added size Prop, and its corresponding variants
- Added the missing states (hover, clicked and focus)
- Removed all colors except "primary".
- Added missing variants - title, underline and bold.
<details>
<summary>📦 Published PR as canary version: <code>20.21.2--canary.522.430848aadf8aa33a9cd4742727fddb964115179c.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.21.2--canary.522.430848aadf8aa33a9cd4742727fddb964115179c.0
yarn add @infineon/infineon-design-system-stencil@20.21.2--canary.522.430848aadf8aa33a9cd4742727fddb96411517 …
```
> Link: Updated in accordance with design view

- README.md
- packages/components/src/stories/setup-and-installation/About.stories.mdx
- packages/components/src/stories/setup-and-installation/GettingStarted.stories.mdx
- packages/components/src/stories/setup-and-installation/framework-integration/ReactWrappers.stories.mdx
- packages/components/src/stories/setup-and-installation/framework-integration/VueWrappers.stories.mdx
Description
update of project readme and gettingStarted file on storybook
<details>
<summary>📦 Published PR as canary version: <code>20.22.0--canary.525.09b3343a8e2719d88622c4e5df3aa6614646d05f.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.22.0--canary.525.09b3343a8e2719d88622c4e5df3aa6614646d05f.0
yarn add @infineon/infineon-design-system-stencil@20.22.0--canary.525.09b3343a8e2719d88622c4e5df3aa6614646d05f.0
```
</details>
> getting started + readme updated

- package-lock.json
- packages/components-vue/lib/components.ts
- packages/components/src/components/tabs/readme.md
- packages/components/src/components/tabs/tab.tsx
- packages/components/src/components/tabs/tabs.scss
- packages/components/src/components/tabs/tabs.stories.tsx
- packages/components/src/components/tabs/tabs.tsx
- packages/components/src/index.html
Description
tab design review changes implemented
<details>
<summary>📦 Published PR as canary version: <code>20.21.5--canary.523.07887c51a605445a28e8a96745ccb068cdc89924.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.21.5--canary.523.07887c51a605445a28e8a96745ccb068cdc89924.0
yarn add @infineon/infineon-design-system-stencil@20.21.5--canary.523.07887c51a605445a28e8a96745ccb068cdc89924.0
```
</details>
> tab design review changes implemented

- README.md
- packages/components-vue/lib/components.ts
- packages/components/src/components/icon/readme.md
- packages/components/src/components/tag/readme.md
- packages/components/src/components/tag/tag.scss
- packages/components/src/components/tag/tag.stories.ts
- packages/components/src/components/tag/tag.tsx
- packages/components/src/index.html
Description
design review changes implemented
<details>
<summary>📦 Published PR as canary version: <code>20.22.2--canary.528.df3d51cc27cbb55fe36a8f4ba275bc91e882597e.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.22.2--canary.528.df3d51cc27cbb55fe36a8f4ba275bc91e882597e.0
yarn add @infineon/infineon-design-system-stencil@20.22.2--canary.528.df3d51cc27cbb55fe36a8f4ba275bc91e882597e.0
```
</details>
> Design review changes: Tag

- package-lock.json
- packages/components/package.json
- packages/components/src/components/footer/footer-column.scss
- packages/components/src/components/footer/footer.scss
- packages/components/src/components/footer/footer.stories.ts
- packages/components/src/components/footer/footer.tsx
- packages/components/src/index.html
- Changed 'default' variant into 'medium'
- Updated the side spacing. Removed the percentage-based width, and replaced it with a side padding of 32px.
- Updated the nested ifx-links to match their latest update as well as the required style when inside the Footer.
- Added the new font-family. 
- Updated the icon library, and included the required icons. 
- Optimized the internal code by removing unnecessary code. 
<details>
<summary>📦 Published PR as canary version: <code>20.22.3--canary.530.0f27f9e1f26bdbc3ccb4d858b75c8e343aaa5f88.0</code></summary>
<br />
```bash …
```
> Footer: updated in accordance with design review

- packages/components/src/components/breadcrumb/breadcrumb.tsx
- packages/components/src/components/navbar/navbar-item.tsx
- packages/components/src/components/pagination/pagination.tsx
- packages/components/src/components/search-bar/search-bar.stories.ts
- packages/components/src/components/sidebar/sidebar.tsx
- packages/components/src/components/table-basic-version/table.scss
- packages/components/src/components/table-basic-version/table.tsx
- packages/components/src/index.html
Description
removed focus from table, navbar and sidebar
fixed missing arg set in story for searchbar
<details>
<summary>📦 Published PR as canary version: <code>20.23.2--canary.540.f9e71910a56440a88d97d48c329d62082492670a.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.23.2--canary.540.f9e71910a56440a88d97d48c329d62082492670a.0
yarn add @infineon/infineon-design-system-stencil@20.23.2--canary.540.f9e71910a56440a88d97d48c329d62082492670a.0
```
</details>
> 537 remove default browser focus from table+sidebar

- examples/wrapper-components/react-javascript/src/components/Pagination/Pagination.js
- packages/components/src/components/pagination/pagination.tsx
- Modified the Pagination inside React example app 
- Reverted back the previously removed ifx-select options. 
<details>
<summary>📦 Published PR as canary version: <code>20.23.5--canary.544.8f3a5204495513f3b48b8103f6fb339ab83f2e59.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.23.5--canary.544.8f3a5204495513f3b48b8103f6fb339ab83f2e59.0
yarn add @infineon/infineon-design-system-stencil@20.23.5--canary.544.8f3a5204495513f3b48b8103f6fb339ab83f2e59.0
```
</details>
> Pagination: per-page items fixed

- packages/components/src/components/sidebar/Usage.mdx
- changed link url in usage.mdx
<details>
<summary>📦 Published PR as canary version: <code>20.23.5--canary.548.508d775b9bc9f57abb3cfbe25962cc98f6f792f3.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.23.5--canary.548.508d775b9bc9f57abb3cfbe25962cc98f6f792f3.0
yarn add @infineon/infineon-design-system-stencil@20.23.5--canary.548.508d775b9bc9f57abb3cfbe25962cc98f6f792f3.0
```
</details>
> Documentation: sidebar update

- packages/components/src/components/button/Usage.mdx
fixed typo in Tertiary
IS: important as the primary or secondary
WAS: important as primary or secondary
Description
Provide the information we need to review your PR. What problem does the pull request solve? "Bug fix" is not a good description.
Related Issue
If you opened an issue before creating the PR, point to it here.
Context
What do we need to know about your development environment, tools, target, and so on. Screenshots are always helpful if there is a UI element to this PR.
<details>
<summary>📦 Published PR as canary version: …
> fixed typo in buttons / tertiary

- packages/components/src/components/select/Usage.mdx
added
"import { Meta } from '@storybook/blocks' "
Description
Provide the information we need to review your PR. What problem does the pull request solve? "Bug fix" is not a good description.
Related Issue
If you opened an issue before creating the PR, point to it here.
Context
What do we need to know about your development environment, tools, target, and so on. Screenshots are always helpful if there is a UI element to this PR.
<details>
<summary>📦 Published PR as canary version: <code>20.23.9--canary.557.0b17e61ede2aa2af6ef85bb2bf2fd87c47eca1f …
> Usage - missing Meta informations fix

- packages/components/src/components/navbar/navbar-item.scss
- packages/components/src/components/navbar/navbar.scss
- packages/components/src/components/navbar/navbar.tsx
- packages/components/src/index.html
<details>
<summary>📦 Published PR as canary version: <code>20.23.10--canary.563.a1654a2f58cd30d753b052abd648e3f31f91911f.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.23.10--canary.563.a1654a2f58cd30d753b052abd648e3f31f91911f.0
yarn add @infineon/infineon-design-system-stencil@20.23.10--canary.563.a1654a2f58cd30d753b052abd648e3f31f91911f.0
```
</details>
> Navbar: updated border-bottom and aligned the items vertically

- packages/components/src/components/tooltip/tooltip.scss
- packages/components/src/components/tooltip/tooltip.tsx
- made with auto on compact version
- adjusted correctly the width on dismissible variant
- if variant Prop is empty, the component defaults to 'compact' variant
- added min-width on dismissible and extended
- aligned icon + text on extended variant
<details>
<summary>📦 Published PR as canary version: <code>20.23.15--canary.593.6038409fe6244b139bdf55af6c72b5839bc1a65f.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.23.15--canary.593.6038409fe6244b139bdf55af6c72b5839bc1a65f.0
yarn add …
```
> Tooltip: small general update

- packages/components-vue/lib/components.ts
- packages/components/src/components/button/button.stories.ts
- packages/components/src/components/button/button.tsx
- packages/components/src/components/button/readme.md
- packages/components/src/index.html
Added a Type property to the Button with a default "button" value, 'reset' and 'submit' when inside a Form element. 
<details>
<summary>📦 Published PR as canary version: <code>20.27.1--canary.665.beb1c3fdf46ab0ad488b65470be7c84d2bb72231.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.27.1--canary.665.beb1c3fdf46ab0ad488b65470be7c84d2bb72231.0
yarn add @infineon/infineon-design-system-stencil@20.27.1--canary.665.beb1c3fdf46ab0ad488b65470be7c84d2bb72231.0
```
</details>
> Button: added a type property

- packages/components/src/components/dropdown/dropdown-trigger-button/dropdown-trigger-button.scss
- packages/components/src/components/dropdown/dropdown-trigger-button/dropdown-trigger-button.tsx
I updated the icon on the trigger-button to point down by default, and rotate right-side to the top 180 degrees.
<details>
<summary>📦 Published PR as canary version: <code>20.30.2--canary.689.ece1f9dd650a73708dc795bba7b3dd2fedfc67b4.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.30.2--canary.689.ece1f9dd650a73708dc795bba7b3dd2fedfc67b4.0
yarn add @infineon/infineon-design-system-stencil@20.30.2--canary.689.ece1f9dd650a73708dc795bba7b3dd2fedfc67b4.0
```
</details>
> Dropdown: v-2 update

- packages/components/src/components/alert/alert.stories.ts
- packages/components/src/components/card/card.scss
- packages/components/src/components/card/card.tsx
- packages/components/src/index.html
Description
checking if the headline exists inside of the card (https://github.com/Infineon/infineon-design-system-stencil/pull/712)
<details>
<summary>📦 Published PR as canary version: <code>20.34.1--canary.716.ad1edfa27ae4f064da76af1666dc7c669bd38956.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.34.1--canary.716.ad1edfa27ae4f064da76af1666dc7c669bd38956.0
yarn add @infineon/infineon-design-system-stencil@20.34.1--canary.716.ad1edfa27ae4f064da76af1666dc7c669bd38 …
```
> Bugfix card - missing headline check

- examples/wrapper-components/react-javascript/src/components/Pagination/Pagination.js
- packages/components/src/components/alert/alert.stories.ts
- packages/components/src/components/pagination/pagination.tsx
- packages/components/src/index.html
Added Math.ceil() when calculating the totalPageNumber. 
<details>
<summary>📦 Published PR as canary version: <code>20.33.1--canary.717.2b2a32b2d705b1ef0484b265f06e9099178f19a1.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.33.1--canary.717.2b2a32b2d705b1ef0484b265f06e9099178f19a1.0
yarn add @infineon/infineon-design-system-stencil@20.33.1--canary.717.2b2a32b2d705b1ef0484b265f06e9099178f19a1.0
```
</details>
> Pagination: updated the calculation algorithm

- examples/stencil-components/vanilla-cdn/index.html
- examples/wrapper-components/react-javascript/package.json
- examples/wrapper-components/react-javascript/src/components/Button/button.js
- examples/wrapper-components/vue-javascript/package.json
- examples/wrapper-components/vue-javascript/src/assets/base.scss
- examples/wrapper-components/vue-javascript/src/assets/main.scss
- examples/wrapper-components/vue-javascript/src/components/Button.vue
- examples/wrapper-components/vue-javascript/src/main.js
- package-lock.json
- packages/components-angular/projects/my-app/src/app/app.component.html
- packages/components-react/package.json
- packages/components-vue/package.json
- packages/components/src/components/button/button.tsx
Description
The button handleClick method didnt have a disabled check. Added to prevent it from being clickable when disabled
<details>
<summary>📦 Published PR as canary version: <code>20.36.2--canary.794.814805cda3dabb0eb9b01c9ca851c907691f7155.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.36.2--canary.794.814805cda3dabb0eb9b01c9ca851c907691f7155.0
yarn add @infineon/infineon-design-system-stencil@20.36.2--canary.794.814805cda3dabb0eb9b01c9ca851c907691f7155.0 …
```
> Bugfix: disabled check added to button component

- .github/workflows/shipit_master_and_example_apps_deployment.yml
Description
Provide the information we need to review your PR. What problem does the pull request solve? "Bug fix" is not a good description.
Related Issue
If you opened an issue before creating the PR, point to it here.
Context
What do we need to know about your development environment, tools, target, and so on. Screenshots are always helpful if there is a UI element to this PR.
<details>
<summary>📦 Published PR as canary version: <code>20.38.3--canary.861.ca71462a676d3c544b9f3ad9c1dbee7e9f5d93ab.0</code></summary>
<br />
:sparkles: Test out …
> bugfix in master .yml

- packages/components/src/components/checkbox/checkbox.tsx
The value prop was being updated internally. I removed it, and optimized the code a little bit.
<details>
<summary>📦 Published PR as canary version: <code>20.43.3--canary.928.5f2a66d06272943da50ed0d6b6eac9f939f45744.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.43.3--canary.928.5f2a66d06272943da50ed0d6b6eac9f939f45744.0
yarn add @infineon/infineon-design-system-stencil@20.43.3--canary.928.5f2a66d06272943da50ed0d6b6eac9f939f45744.0
```
</details>
> Checkbox: optimized internal state usage

- packages/components/src/components/select/multi-select/multiselect.scss
- packages/components/src/components/select/single-select/select.scss
- packages/components/src/components/text-field/text-field.scss
Description
Fixed and aligned the text, border, hover, spacing etc. of selected and text field.
Related Issue
https://github.com/Infineon/infineon-design-system-stencil/issues/947
Context
A bug was reported that select and text field are not aligned
<details>
<summary>📦 Published PR as canary version: <code>20.44.1--canary.948.f8f69014d36e74d42d696131f461bd0b3cca5178.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@20.44.1--canary.948.f8f69014d36e74d42d696131f461bd0b3 …
```
> Bugfix: text field uses wrong font size and styling not aligned

- .github/workflows/shipit_master_and_example_apps_deployment.yml
- lerna.json
- package-lock.json
- packages/components-angular/package.json
- packages/components-angular/projects/component-library/package.json
- packages/components-react/package.json
- packages/components-vue/package.json
- packages/components/package.json
Description
see issue
<details>
<summary>📦 Published PR as canary version: <code>25.2.2--canary.1512.ca7e195752a049d5396838ead8ee2f0401dceee8.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@25.2.2--canary.1512.ca7e195752a049d5396838ead8ee2f0401dceee8.0
yarn add @infineon/infineon-design-system-stencil@25.2.2--canary.1512.ca7e195752a049d5396838ead8ee2f0401dceee8.0
```
</details>
> Bugfix: Deployment of React Example App Master version

- .github/workflows/shipit_master_and_example_apps_deployment.yml
- .github/workflows/shipit_pr_and_example_apps_deployment.yml
- examples/stencil-components/vanilla-cdn/index.html
- examples/wrapper-components/react-javascript/src/App.js
- examples/wrapper-components/react-javascript/src/components/ContentSwitcher/ContentSwitcher.js
- examples/wrapper-components/react-vite-js/package-lock.json
- examples/wrapper-components/react-vite-js/package.json
- examples/wrapper-components/react-vite-js/src/App.jsx
- examples/wrapper-components/react-vite-js/src/components/ContentSwitcher/ContentSwitcher.jsx
- examples/wrapper-components/react-vite-js/vite.config.js
- examples/wrapper-components/vue-javascript/package.json
- examples/wrapper-components/vue-javascript/src/App.vue
- examples/wrapper-components/vue-javascript/src/components/ContentSwitcher.vue
- lerna.json
- package-lock.json
- packages/components-angular/package.json
- packages/components-angular/projects/component-library/package.json
- packages/components-angular/projects/component-library/src/lib/stencil-generated/index.ts
- packages/components-angular/projects/my-app/src/app/app.component.html
- packages/components-react/package.json
- packages/components-react/src/components.ts
- packages/components-vue/package.json
- packages/components/package.json
- packages/components/src/components/content-switcher/content-switcher-item.scss
- packages/components/src/components/content-switcher/content-switcher-item.tsx
- packages/components/src/components/content-switcher/content-switcher.e2e.ts
- packages/components/src/components/content-switcher/content-switcher.scss
- packages/components/src/components/content-switcher/content-switcher.stories.ts
- packages/components/src/components/content-switcher/content-switcher.tsx
- packages/components/src/components/content-switcher/readme.md
Description
Adds the Content Switcher Component.
Related Issue
Closing #1432 
Context
<details>
<summary>📦 Published PR as canary version: <code>25.8.0--canary.1474.33d0c70051c87a15c56093ef6c47c51decdde43c.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@25.8.0--canary.1474.33d0c70051c87a15c56093ef6c47c51decdde43c.0
yarn add @infineon/infineon-design-system-stencil@25.8.0--canary.1474.33d0c70051c87a15c56093ef6c47c51decdde43c.0
```
</details>
> Enhancement: Add content-switcher component

- examples/stencil-components/vanilla-cdn/index.html
- examples/wrapper-components/react-vite-js/package-lock.json
- examples/wrapper-components/react-vite-js/package.json
- examples/wrapper-components/react-vite-js/src/App.jsx
- examples/wrapper-components/react-vite-js/src/components/CheckboxGroup/CheckboxGroup.jsx
- examples/wrapper-components/vue-javascript/package.json
- examples/wrapper-components/vue-javascript/src/App.vue
- examples/wrapper-components/vue-javascript/src/components/CheckboxGroup.vue
- lerna.json
- package-lock.json
- packages/components-angular/package.json
- packages/components-angular/projects/component-library/package.json
- packages/components-angular/projects/component-library/src/lib/stencil-generated/index.ts
- packages/components-angular/projects/my-app/src/app/app.component.html
- packages/components-react/package.json
- packages/components-react/src/components.ts
- packages/components-vue/package.json
- packages/components/package.json
- packages/components/src/components/checkbox-group/checkbox-group.e2e.ts
- packages/components/src/components/checkbox-group/checkbox-group.scss
- packages/components/src/components/checkbox-group/checkbox-group.stories.ts
- packages/components/src/components/checkbox-group/checkbox-group.tsx
- packages/components/src/components/checkbox-group/readme.md
- packages/components/src/components/checkbox/checkbox.scss
- packages/components/src/components/checkbox/checkbox.stories.ts
- packages/components/src/components/checkbox/checkbox.tsx
- packages/components/src/components/checkbox/readme.md
- packages/components/src/components/icon/readme.md
Description
New Component: Checkbox Group
Related Issue
#1417 
<details>
<summary>📦 Published PR as canary version: <code>32.1.0--canary.1681.de13163f46db2951612558fb9ef687c8e4b40763.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@32.1.0--canary.1681.de13163f46db2951612558fb9ef687c8e4b40763.0
yarn add @infineon/infineon-design-system-stencil@32.1.0--canary.1681.de13163f46db2951612558fb9ef687c8e4b40763.0
```
</details>
> New component: Checkbox-group

- examples/wrapper-components/react-vite-js/package.json
- examples/wrapper-components/vue-javascript/package.json
- lerna.json
- package-lock.json
- packages/components-angular/package.json
- packages/components-angular/projects/component-library/package.json
- packages/components-react/package.json
- packages/components-vue/package.json
- packages/components/package.json
- packages/components/src/components/icon/infineonIconStencil.tsx
Description
Using updated icon names after reverting back to camelCase names in the icons-library
https://github.com/Infineon/Infineon-Icons/pull/89
<details>
<summary>📦 Published PR as canary version: <code>35.2.1--canary.1915.7ab6592d308edd014242f541701f87632b3f48d5.0</code></summary>
<br />
```bash
npm install @infineon/infineon-design-system-stencil@35.2.1--canary.1915.7ab6592d308edd014242f541701f87632b3f48d5.0
yarn add @infineon/infineon-design-system-stencil@35.2.1--canary.1915.7ab6592d308edd014242f …
```
> Updates icon name validation to only accept camelCase and kebab-case
